//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppBlogMVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BlogDbEntities : DbContext
    {
        public BlogDbEntities()
            : base("name=BlogDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__EFMigrationsHistory> C__EFMigrationsHistory { get; set; }
        public virtual DbSet<AdminInfo> AdminInfoes { get; set; }
        public virtual DbSet<BlogInfo> BlogInfoes { get; set; }
        public virtual DbSet<EmpInfo> EmpInfoes { get; set; }

        public System.Data.Entity.DbSet<WebAppBlogMVC.Models.Login> Logins { get; set; }
    }
}
